version: '3.8'

services:
  user_access_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  event_sender:
    build:
      context: ./event_sender
      dockerfile: Dockerfile
    environment:
      EVENT_URL: "http://user_access_service:5000/event"
    depends_on:
      - user_access_service
